### ISSUE TITLE
Connexion au serveur X11

### ISSUE THREAD

**Issue by rlecomte** [agileek/docker-ansible#1]
Salut Michael,

Il me semble que si tu n'installes pas le paquet X11-utils dans le docker, la connexion au serveur graphique ne fonctionne pas.

testé avec intellij -> erreur java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit

Après l'installation du paquet, ça fonctionne.

**Comment by MichaelBitard** [comment]
T'aurais pu faire une pull request ;)

Je corrige ça, j'en profite pour merger la branche dockerception que j'avais pas faite encore
